/* ============================================================
   Seiteninhalte (Body-HTML pro Route). Nutzt templates.js.
   ============================================================ */

var SPEC_YIELD = { nord:950, mitte:1020, sued:1100 };

function calcStatic(){
  var CP = prod('one-plus'); var region='sued'; var strom=35;
  var yieldKwh = Math.round(CP.kwp * SPEC_YIELD[region]);
  var savings = yieldKwh * strom / 100;
  return { yieldKwh:yieldKwh, savings:savings, amort:CP.price/savings, ers25:savings*25, CP:CP };
}
function calcNote(CP){ return 'Berechnung auf Basis des ' + CP.name + ' mit ' + CP.wp + ' Wp-Solarmodul, optimal geneigt um 25°. Richtwerte bei vollständiger Eigennutzung des erzeugten Stroms.'; }
function calcProductsHtml(activeId){
  return PRODUCTS.map(function(p){
    var active = activeId === p.id;
    var style = 'flex:1; cursor:pointer; text-align:center; padding:13px 8px; border-radius:14px; transition:all .15s; border:1.5px solid ' + (active?'#111113':'#d2d2d7') + '; background:' + (active?'#111113':'#ffffff') + '; color:' + (active?'#ffffff':'#1d1d1f') + ';';
    var subStyle = 'font-size:12px; margin-top:2px; color:' + (active?'rgba(255,255,255,0.7)':'#86868b') + ';';
    return '<button type="button" data-calc-select="'+p.id+'" style="'+style+'"><div style="font-weight:700; font-size:15px;">'+p.shortLabel+'</div><div style="'+subStyle+'">'+p.wp+' Wp</div></button>';
  }).join('');
}

/* ---------------- HOME ---------------- */
function pageHome(){
  var v = calcStatic();
  return ''
  + '<section class="hero" style="position:relative; overflow:hidden; background-image:linear-gradient(180deg, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0) 24%), linear-gradient(90deg, rgba(255,255,255,0.98) 0%, rgba(255,255,255,0.93) 38%, rgba(255,255,255,0.55) 58%, rgba(255,255,255,0.1) 80%, rgba(255,255,255,0) 95%), url(\'/assets/hero-v5.png\'); background-size:cover; background-position:right center; min-height:620px; display:flex; align-items:center;">'
  +   '<div class="hero-inner" style="max-width:1280px; width:100%; margin:0 auto; padding:90px 32px 110px;">'
  +     '<h1 style="margin:0 0 26px; font-size:56px; line-height:1.12; font-weight:600; letter-spacing:-0.02em; color:#1d1d1f; max-width:720px;">Der Solartisch, der deine <span class="shimmer" style="color:#e8821d; font-weight:700;">Stromabrechnung</span> kürzt.</h1>'
  +     '<p style="margin:0 0 38px; font-size:19px; line-height:1.6; color:#424245; max-width:500px;">Der Solartisch Sustable ONE verbindet Design mit Nachhaltigkeit. Ein eleganter Gartentisch, der Sonnenenergie in Strom für dein Zuhause verwandelt.</p>'
  +     '<div class="stack-sm" style="display:flex; gap:14px; flex-wrap:wrap;">'
  +       '<a href="/shop/" style="cursor:pointer; display:inline-flex; align-items:center; gap:9px; background:#111113; color:#ffffff; border-radius:980px; padding:14px 30px; font-weight:600; font-size:16px;">Jetzt entdecken '+arrowW+'</a>'
  +       '<a href="#rechner" style="cursor:pointer; display:inline-flex; align-items:center; justify-content:center; background:rgba(255,255,255,0.7); color:#1d1d1f; border:1.5px solid #86868b; border-radius:980px; padding:13px 28px; font-weight:600; font-size:16px;">Ersparnis berechnen</a>'
  +     '</div>'
  +   '</div>'
  + '</section>'
  + '<section id="rechner" style="background:#f5f5f7; padding:100px 32px;">'
  +   '<div style="max-width:1180px; margin:0 auto;">'
  +     '<div style="text-align:center; margin-bottom:54px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Rechner</div><h2 style="margin:0; font-size:42px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Deine mögliche Ersparnis.</h2></div>'
  +     '<div class="grid2" style="display:grid; grid-template-columns:1.1fr 1fr; gap:24px; align-items:stretch;">'
  +       '<div class="calc-pad" style="background:#ffffff; border-radius:22px; padding:44px; display:flex; flex-direction:column; gap:36px;">'
  +         '<div><label style="display:block; font-weight:600; font-size:15px; color:#1d1d1f; margin-bottom:12px;">Dein Solartisch</label><div id="calc-products" style="display:flex; gap:8px;">'+calcProductsHtml('one-plus')+'</div></div>'
  +         '<div><div style="display:flex; justify-content:space-between; align-items:baseline; margin-bottom:14px;"><label for="calc-strom-input" style="font-weight:600; font-size:15px; color:#1d1d1f;">Dein Strompreis</label><span style="font-weight:700; font-size:22px; color:#1d1d1f;"><span id="calc-strom">35</span> ct/kWh</span></div>'
  +           '<input id="calc-strom-input" type="range" min="20" max="60" step="1" value="35" style="width:100%; accent-color:#111113; cursor:pointer; height:28px;">'
  +           '<div style="display:flex; justify-content:space-between; font-size:12.5px; color:#86868b; margin-top:4px;"><span>20 ct</span><span>60 ct</span></div></div>'
  +         '<div><label for="calc-region" style="display:block; font-weight:600; font-size:15px; color:#1d1d1f; margin-bottom:12px;">Dein Standort</label>'
  +           '<select id="calc-region" style="width:100%; padding:14px 16px; font-size:15px; border:1px solid #d2d2d7; border-radius:12px; background:#ffffff; color:#1d1d1f; cursor:pointer;"><option value="nord">Norddeutschland · ca. 950 kWh/kWp im Jahr</option><option value="mitte">Mitteldeutschland · ca. 1.020 kWh/kWp im Jahr</option><option value="sued" selected>Süddeutschland · ca. 1.100 kWh/kWp im Jahr</option></select></div>'
  +         '<p id="calc-note" style="margin:0; font-size:12.5px; line-height:1.6; color:#86868b;">'+calcNote(v.CP)+'</p>'
  +       '</div>'
  +       '<div class="calc-pad" style="background:#0a0a0c; border-radius:22px; padding:44px; color:#ffffff; display:flex; flex-direction:column; justify-content:center; gap:30px;">'
  +         '<div><div style="font-size:14px; font-weight:500; color:#86868b; margin-bottom:8px;">Deine Ersparnis pro Jahr</div><div id="calc-ersparnis" class="calc-big" style="font-size:56px; font-weight:700; letter-spacing:-0.02em; color:#ffffff; line-height:1;">'+fmtEur(v.savings)+'</div></div>'
  +         '<div class="calc-stats" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:18px; border-top:1px solid rgba(255,255,255,0.14); padding-top:28px;">'
  +           '<div><div id="calc-ertrag" style="font-size:21px; font-weight:700;">'+v.yieldKwh.toLocaleString('de-DE')+' kWh</div><div style="font-size:12.5px; color:#86868b; margin-top:4px;">Stromertrag pro Jahr</div></div>'
  +           '<div><div id="calc-amort" style="font-size:21px; font-weight:700;">'+v.amort.toLocaleString('de-DE',{maximumFractionDigits:1})+' Jahre</div><div style="font-size:12.5px; color:#86868b; margin-top:4px;">Amortisationszeit</div></div>'
  +           '<div><div id="calc-ersparnis25" style="font-size:21px; font-weight:700;">'+fmtEur(v.ers25)+'</div><div style="font-size:12.5px; color:#86868b; margin-top:4px;">Ersparnis in 25 Jahren</div></div>'
  +         '</div>'
  +         '<a href="/shop/" style="cursor:pointer; align-self:flex-start; display:inline-flex; align-items:center; gap:9px; background:#ffffff; color:#111113; border-radius:980px; padding:12px 26px; font-weight:600; font-size:15px;">Jetzt entdecken '+arrowD+'</a>'
  +       '</div>'
  +     '</div>'
  +   '</div>'
  + '</section>'
  + '<section style="padding:110px 32px; background:#ffffff;"><div style="max-width:1180px; margin:0 auto;">'
  +   '<div style="text-align:center; margin-bottom:60px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Vorteile</div><h2 style="margin:0 0 18px; font-size:42px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Warum ein Sustable Solartisch?</h2><p style="margin:0 auto; max-width:600px; font-size:17px; line-height:1.6; color:#6e6e73;">Mehr als nur ein Gartentisch. Eine Investition in Nachhaltigkeit, Design und deine Unabhängigkeit.</p></div>'
  +   '<div class="grid3" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:20px;">'
  +     benefit('<circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="M4.93 4.93l1.41 1.41"></path><path d="M17.66 17.66l1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path><path d="M6.34 17.66l-1.41 1.41"></path><path d="M19.07 4.93l-1.41 1.41"></path>','Solarenergie nutzen','Wandelt Sonnenlicht in sauberen Strom für dein Zuhause um, direkt auf deiner Terrasse.')
  +     benefit('<path d="M4 10h12"></path><path d="M4 14h9"></path><path d="M19 6a7.7 7.7 0 0 0-5.2-2A7.9 7.9 0 0 0 6 12c0 4.4 3.5 8 7.8 8 2 0 3.8-.8 5.2-2"></path>','Kosten sparen','Senke deine Stromrechnung nachhaltig und mache dich unabhängiger vom Stromnetz.')
  +     benefit('<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"></path><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"></path>','Nachhaltig leben','Regional und fair produziert. Ein Beitrag zu einer sauberen Zukunft.')
  +     benefit('<path d="M12 22v-5"></path><path d="M9 8V2"></path><path d="M15 8V2"></path><path d="M18 8v5a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V8Z"></path>','Plug &amp; Play','Ansteckkabel in die Außensteckdose stecken und Strom direkt ins Haus einspeisen.')
  +     benefit('<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1 1 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path>','10 Jahre Garantie','Hochwertige Materialien und deutsche Qualität für langfristige Zuverlässigkeit.')
  +     benefit('<path d="M19 9V6a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v3"></path><path d="M3 16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v2H7v-2a2 2 0 0 0-4 0Z"></path><path d="M5 18v2"></path><path d="M19 18v2"></path>','Design &amp; Komfort','Genieße vollen Gartentisch-Komfort und modernes Design trotz integrierter Solartechnik.')
  +   '</div></div></section>'
  + productTeaser()
  + appSection()
  + dealerTeaser()
  + manufactureSection();
}
function productTeaser(){
  return '<section style="padding:100px 32px; background:#f5f5f7;"><div class="grid2" style="max-width:1180px; margin:0 auto; display:grid; grid-template-columns:1fr 1fr; gap:60px; align-items:center;">'
  + '<div style="background:#ffffff; border-radius:22px; padding:40px; display:flex; align-items:center; justify-content:center;"><img src="https://sustable.eu/wp-content/uploads/2025/10/One_1.avif" alt="Solartisch Sustable ONE+ aus gebürstetem Edelstahl" loading="lazy" style="max-width:100%; height:auto; display:block;"></div>'
  + '<div><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Das Produkt</div><h2 style="margin:0 0 20px; font-size:38px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Sustable ONE+ Edelstahl.</h2>'
  + '<p style="margin:0 0 26px; font-size:16px; line-height:1.7; color:#6e6e73;">Eleganter Solartisch aus gebürstetem Edelstahl mit integriertem 465 Wp-Solarmodul und 500 W-Wechselrichter. Mit versenkbaren Rollen mobil auf deiner Terrasse – die Gasdruckdämpfer neigen ihn in den perfekten Winkel von 25°.</p>'
  + '<div style="font-size:28px; font-weight:700; color:#1d1d1f; margin-bottom:30px;">1.750 €</div>'
  + '<div style="display:flex; gap:14px; flex-wrap:wrap;"><button type="button" data-add="one-plus" style="cursor:pointer; display:inline-flex; align-items:center; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:13px 28px; font-weight:600; font-size:15px;">In den Warenkorb</button>'
  + '<a href="'+productPath(prod('one-plus'))+'" style="cursor:pointer; display:inline-flex; align-items:center; background:transparent; color:#1d1d1f; border:1.5px solid #c7c7cc; border-radius:980px; padding:12px 26px; font-weight:600; font-size:15px;">Mehr erfahren</a></div></div></div></section>';
}
function appSection(){
  return '<section style="padding:110px 32px; background:#0a0a0c;"><div class="grid2" style="max-width:1180px; margin:0 auto; display:grid; grid-template-columns:1.1fr 1fr; gap:70px; align-items:center;">'
  + '<div><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">App</div><h2 style="margin:0 0 20px; font-size:42px; font-weight:700; letter-spacing:-0.02em; color:#ffffff; line-height:1.15;">Alles auf einen Blick.<br>In der App.</h2><p style="margin:0 0 38px; font-size:16.5px; line-height:1.7; color:#86868b; max-width:440px;">Verfolge live, wie viel Strom dein Sustable erzeugt – und wie viel du sparst.</p><div style="display:flex; flex-direction:column;">'
  + appRow('<path d="M13 2 4.09 12.69A1 1 0 0 0 5 14h4v8l8.91-10.69A1 1 0 0 0 17 10h-4z"></path>','Live-Ertrag','Aktuelle Leistung in Watt, in Echtzeit', false)
  + appRow('<path d="M3 3v16a2 2 0 0 0 2 2h16"></path><path d="M7 14l4-4 3 3 5-6"></path>','Tages- und Jahresverlauf','Erzeugung pro Tag, Monat und Jahr', false)
  + appRow('<path d="M4 10h12"></path><path d="M4 14h9"></path><path d="M19 6a7.7 7.7 0 0 0-5.2-2A7.9 7.9 0 0 0 6 12c0 4.4 3.5 8 7.8 8 2 0 3.8-.8 5.2-2"></path>','Ersparnis in Euro','Dein Beitrag zur Stromrechnung, mitgerechnet', true)
  + '</div></div>'
  + '<div style="display:flex; justify-content:center;"><div style="width:300px; background:#0a0a0c; border-radius:48px; padding:11px; box-shadow:0 40px 90px rgba(0,0,0,0.55), inset 0 0 0 2px rgba(255,255,255,0.07); position:relative;"><div style="position:absolute; top:22px; left:50%; transform:translateX(-50%); width:96px; height:26px; background:#000000; border-radius:999px; z-index:2;"></div><img src="/assets/app-screen.png" alt="Sustable App mit Live-Ertrag des Solartischs" loading="lazy" style="display:block; width:100%; border-radius:38px;"></div></div>'
  + '</div></section>';
}
function dealerTeaser(){
  return '<section style="padding:110px 32px; background:#ffffff;"><div style="max-width:1180px; margin:0 auto; text-align:center;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Vor Ort erleben</div><h2 style="margin:0 0 18px; font-size:38px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Sustable bei einem Händler in deiner Nähe.</h2><p style="margin:0 auto 40px; max-width:540px; font-size:16.5px; line-height:1.6; color:#6e6e73;">Erlebe den Sustable ONE+ live – bei unseren Fachhändlern in Koblenz und Memmingen.</p>'
  + '<div style="display:flex; gap:18px; justify-content:center; flex-wrap:wrap; margin-bottom:40px;"><div style="background:#f5f5f7; border-radius:20px; padding:26px 34px; text-align:left; min-width:290px;"><div style="font-weight:700; font-size:16px; margin-bottom:6px;">BÜRO-CREATIV GmbH</div><div style="font-size:14.5px; color:#6e6e73; line-height:1.6;">Schönbornsluster Straße 53<br>56070 Koblenz</div></div><div style="background:#f5f5f7; border-radius:20px; padding:26px 34px; text-align:left; min-width:290px;"><div style="font-weight:700; font-size:16px; margin-bottom:6px;">Möbel Wassermann</div><div style="font-size:14.5px; color:#6e6e73; line-height:1.6;">Mittereschweg 2<br>87700 Memmingen</div></div></div>'
  + '<a href="/haendlersuche/" style="cursor:pointer; display:inline-flex; align-items:center; gap:9px; background:#111113; color:#ffffff; border-radius:980px; padding:14px 30px; font-weight:600; font-size:15px;">Händler auf der Karte finden '+arrowW+'</a></div></section>';
}
function manufactureSection(){
  return '<section style="padding:100px 32px 120px; background:#f5f5f7;"><div style="max-width:1180px; margin:0 auto; text-align:center;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Herstellung</div><h2 style="margin:0 0 44px; font-size:38px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Regional und fair gefertigt.</h2><div style="max-width:800px; margin:0 auto; border-radius:22px; overflow:hidden; box-shadow:0 24px 60px rgba(0,0,0,0.16); background:#0a0a0c;"><video src="https://sustable.eu/wp-content/uploads/2025/10/Fertigung.mp4" controls preload="none" poster="https://sustable.eu/wp-content/uploads/2026/03/DSC04368-2048x1365.jpg" style="width:100%; display:block;"></video></div></div></section>';
}

/* ---------------- PRODUKT ---------------- */
function pageProdukt(SP){
  return '<div style="background:#ffffff; padding:50px 32px 120px;"><div style="max-width:1180px; margin:0 auto;">'
  + '<nav aria-label="Brotkrumen" style="font-size:13.5px; color:#86868b; margin-bottom:36px;"><a href="/" style="color:#86868b;">Start</a><span> / </span><a href="/shop/" style="color:#86868b;">Shop</a><span> / </span><span style="color:#1d1d1f; font-weight:600;">'+esc(SP.fullName)+'</span></nav>'
  + '<div class="grid2" style="display:grid; grid-template-columns:1.1fr 1fr; gap:56px; align-items:start;">'
  + '<div class="pd-img" style="border-radius:22px; overflow:hidden; background:#f5f5f7; height:480px;"><img src="'+SP.img+'" alt="'+esc(SP.fullName)+'" width="800" height="800" style="width:100%; height:100%; object-fit:cover; display:block;"></div>'
  + '<div><h1 style="margin:0 0 14px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">'+esc(SP.fullName)+'</h1><div style="font-size:30px; font-weight:700; color:#1d1d1f; margin-bottom:6px;">'+fmtEur(SP.price)+'</div><div style="font-size:13px; color:#86868b; margin-bottom:26px;">inkl. MwSt. · zzgl. Versand</div><p style="margin:0 0 26px; font-size:15px; line-height:1.7; color:#6e6e73;">'+esc(SP.desc)+'</p>'
  + '<ul style="margin:0 0 30px; padding:0; list-style:none; display:flex; flex-direction:column; gap:10px; font-size:14.5px; color:#1d1d1f;">'
  + '<li style="display:flex; gap:12px; align-items:center;">'+check+SP.wp+' Wp-Solarmodul, 500 W-Wechselrichter</li>'
  + '<li style="display:flex; gap:12px; align-items:center;">'+check+'Per Gasdruckdämpfer neigbar in den optimalen 25°-Winkel</li>'
  + '<li style="display:flex; gap:12px; align-items:center;">'+check+'Im Tischfuß versenkbare Rollen – mobil auf der Terrasse</li>'
  + '<li style="display:flex; gap:12px; align-items:center;">'+check+'Wetterfest, Made in Germany, 10 Jahre Garantie</li></ul>'
  + '<div style="display:flex; gap:14px; align-items:stretch; margin-bottom:18px;"><div style="display:flex; align-items:center; border:1.5px solid #c7c7cc; border-radius:980px; overflow:hidden;"><button type="button" id="pd-dec" aria-label="Menge verringern" style="cursor:pointer; padding:12px 18px; font-size:18px; font-weight:600; color:#1d1d1f; background:none; border:0;">−</button><span id="pd-qty" style="min-width:36px; text-align:center; font-weight:700; font-size:16px;">1</span><button type="button" id="pd-inc" aria-label="Menge erhöhen" style="cursor:pointer; padding:12px 18px; font-size:18px; font-weight:600; color:#1d1d1f; background:none; border:0;">+</button></div>'
  + '<button type="button" data-add="'+SP.id+'" data-add-qty="pd-qty" style="cursor:pointer; flex:1; display:inline-flex; align-items:center; justify-content:center; gap:10px; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:14px 28px; font-weight:600; font-size:16px;">In den Warenkorb</button></div>'
  + '<div style="font-size:13.5px; color:#424245; background:#f5f5f7; border-radius:14px; padding:14px 18px; line-height:1.6;"><span style="font-weight:700;">Plug &amp; Play:</span> Ansteckkabel in die Außensteckdose stecken und Strom direkt ins Haus einspeisen – ohne Installation.</div>'
  + '<div style="margin-top:36px;"><h2 style="margin:0 0 14px; font-size:18px; font-weight:700; color:#1d1d1f;">Technische Daten</h2><div style="display:grid; grid-template-columns:1fr 1fr; border-top:1px solid #e8e8ed; font-size:14px;">'
  + techRow('Solarmodul', SP.wp+' Wp') + techRow('Wechselrichter','500 W') + techRow('Material', SP.material) + techRow('Maße', SP.masse) + techRow('Neigung','25° per Gasdruckdämpfer') + techRow('Garantie','10 Jahre')
  + '</div></div></div></div></div></div>';
}

/* ---------------- SHOP ---------------- */
function pageShop(){
  var cards = PRODUCTS.map(function(p){
    return '<div style="background:#ffffff; border-radius:22px; overflow:hidden; display:flex; flex-direction:column;">'
    + '<a href="'+productPath(p)+'" style="cursor:pointer; height:270px; background:#f5f5f7; overflow:hidden; display:block;"><img src="'+p.img+'" alt="'+esc(p.fullName)+'" loading="lazy" style="width:100%; height:100%; object-fit:cover; display:block;"></a>'
    + '<div style="padding:30px; display:flex; flex-direction:column; gap:14px; flex:1;"><div style="display:inline-flex;"><span style="background:#f5f5f7; color:#424245; font-size:12px; font-weight:600; padding:6px 13px; border-radius:980px;">'+p.badge+'</span></div>'
    + '<h2 style="margin:0; font-size:21px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;"><a href="'+productPath(p)+'" style="color:#1d1d1f;">'+p.name+'</a></h2>'
    + '<p style="margin:0; font-size:14px; line-height:1.6; color:#6e6e73;">'+p.desc+'</p>'
    + '<div style="margin-top:auto; display:flex; flex-direction:column; gap:16px; padding-top:8px;"><div style="font-size:24px; font-weight:700; color:#1d1d1f;">'+fmtEur(p.price)+'</div>'
    + '<div style="display:flex; gap:10px; flex-wrap:wrap;"><button type="button" data-add="'+p.id+'" style="cursor:pointer; flex:1; text-align:center; display:inline-flex; align-items:center; justify-content:center; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:11px 18px; font-weight:600; font-size:14px;">In den Warenkorb</button>'
    + '<a href="'+productPath(p)+'" style="cursor:pointer; display:inline-flex; align-items:center; justify-content:center; background:transparent; color:#1d1d1f; border:1.5px solid #c7c7cc; border-radius:980px; padding:10px 18px; font-weight:600; font-size:14px;">Details</a></div></div></div></div>';
  }).join('');
  return '<div style="background:#f5f5f7; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:1180px; margin:0 auto;"><div style="text-align:center; margin-bottom:56px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Shop</div><h1 style="margin:0 0 16px; font-size:46px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Unsere Solartische.</h1><p style="margin:0; font-size:17px; color:#6e6e73;">Made in Germany · 10 Jahre Garantie · Plug &amp; Play</p></div>'
  + '<div class="grid3" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:24px;">'+cards+'</div>'
  + '<p style="text-align:center; font-size:12.5px; color:#86868b; margin:32px 0 0;">Lieferzeit ca. 2–3 Wochen · Versand innerhalb Deutschlands · Demo-Shop</p></div></div>';
}

/* ---------------- FAQ (als <details>, crawlbar) ---------------- */
function pageFaq(){
  var groups = FAQS.map(function(g){
    var items = g.items.map(function(f){
      return '<details style="background:#f5f5f7; border-radius:16px; overflow:hidden;"><summary style="display:flex; justify-content:space-between; align-items:center; gap:16px; padding:20px 26px; color:#1d1d1f; font-weight:600; font-size:15.5px;">'+esc(f.q)+'<span class="faq-plus" style="font-size:22px; font-weight:500; color:#1d1d1f; flex-shrink:0; line-height:1;">+</span></summary><div style="padding:0 26px 22px; font-size:14.5px; line-height:1.75; color:#6e6e73;">'+esc(f.a)+'</div></details>';
    }).join('');
    return '<div style="margin-bottom:40px;"><h2 style="margin:0 0 16px; font-size:19px; font-weight:700; color:#1d1d1f;">'+g.cat+'</h2><div style="display:flex; flex-direction:column; gap:10px;">'+items+'</div></div>';
  }).join('');
  return '<div style="background:#ffffff; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:840px; margin:0 auto;"><div style="text-align:center; margin-bottom:56px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">FAQ</div><h1 style="margin:0 0 16px; font-size:46px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Häufige Fragen zum Solartisch.</h1><p style="margin:0; font-size:17px; color:#6e6e73;">Alles Wichtige rund um deinen Sustable Solartisch.</p></div>'
  + groups
  + '<div style="background:#0a0a0c; border-radius:22px; padding:44px; text-align:center; margin-top:20px;"><h2 style="margin:0 0 10px; font-size:22px; font-weight:700; color:#ffffff;">Deine Frage war nicht dabei?</h2><p style="margin:0 0 26px; font-size:14.5px; color:#86868b;">Schreib uns – wir melden uns innerhalb von 24 Stunden.</p><a href="mailto:louis.mueller@sustable.eu" style="display:inline-flex; align-items:center; background:#ffffff; color:#111113; border-radius:980px; padding:12px 26px; font-weight:600; font-size:14.5px;">Kontakt aufnehmen</a></div></div></div>';
}

/* ---------------- BLOG ---------------- */
function pageBlogIndex(){
  var f = BLOG_POSTS[0];
  var rest = BLOG_POSTS.slice(1);
  var restHtml = rest.map(function(b){
    return '<a href="/blog/'+b.id+'/" style="background:#ffffff; border-radius:22px; overflow:hidden; color:#1d1d1f; display:flex; flex-direction:column; cursor:pointer;"><img src="'+b.img+'" alt="'+esc(b.title)+'" loading="lazy" style="width:100%; height:200px; object-fit:cover; display:block; background:#f5f5f7;"><div style="padding:28px; display:flex; flex-direction:column; gap:10px; flex:1;"><span style="font-size:13px; color:#86868b;">'+b.date+'</span><h2 style="margin:0; font-size:17.5px; line-height:1.4; font-weight:700;">'+b.title+'</h2><p style="margin:0; font-size:14px; line-height:1.6; color:#6e6e73;">'+b.excerpt+'</p><span style="color:#1d1d1f; font-weight:600; font-size:14px; margin-top:auto;">Weiterlesen →</span></div></a>';
  }).join('');
  return '<div style="background:#f5f5f7; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:1180px; margin:0 auto;"><div style="text-align:center; margin-bottom:56px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Blog</div><h1 style="margin:0 0 16px; font-size:46px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Neues von Sustable.</h1><p style="margin:0; font-size:17px; color:#6e6e73;">Einblicke in unsere Journey, Micro-PV und die Energiewende für alle.</p></div>'
  + '<a href="/blog/'+f.id+'/" class="grid2" style="display:grid; grid-template-columns:1.2fr 1fr; background:#ffffff; border-radius:22px; overflow:hidden; margin-bottom:24px; color:#1d1d1f; cursor:pointer;"><img src="'+f.img+'" alt="'+esc(f.title)+'" style="width:100%; height:380px; object-fit:cover; display:block;"><div style="padding:44px; display:flex; flex-direction:column; justify-content:center; gap:14px;"><div style="display:flex; align-items:center; gap:12px;"><span style="background:#f5f5f7; color:#1d1d1f; font-size:12.5px; font-weight:600; padding:6px 14px; border-radius:980px;">Aktueller Beitrag</span><span style="font-size:13px; color:#86868b;">'+f.date+'</span></div><h2 style="margin:0; font-size:25px; line-height:1.3; font-weight:700; letter-spacing:-0.01em;">'+f.title+'</h2><p style="margin:0; font-size:14.5px; line-height:1.65; color:#6e6e73;">'+f.excerpt+'</p><span style="color:#1d1d1f; font-weight:600; font-size:14.5px;">Weiterlesen →</span></div></a>'
  + '<div class="grid3" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:20px;">'+restHtml+'</div></div></div>';
}
function pageBlogPost(post){
  var body = post.body.map(function(p){ return '<p style="margin:0; font-size:16.5px; line-height:1.8; color:#2c2c2e;">'+esc(p)+'</p>'; }).join('');
  return '<div style="background:#f5f5f7; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:760px; margin:0 auto;"><a href="/blog/" style="cursor:pointer; display:inline-flex; align-items:center; color:#6e6e73; font-weight:600; font-size:14.5px; margin-bottom:28px;">← Alle Beiträge</a>'
  + '<div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">'+post.cat+' · '+post.date+'</div>'
  + '<h1 style="margin:0 0 28px; font-size:38px; line-height:1.18; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">'+esc(post.title)+'</h1>'
  + '<img src="'+post.img+'" alt="'+esc(post.title)+'" style="width:100%; height:380px; object-fit:cover; display:block; border-radius:22px; margin-bottom:36px;">'
  + '<div style="display:flex; flex-direction:column; gap:20px;">'+body+'</div>'
  + '<div style="margin-top:44px; padding-top:32px; border-top:1px solid #e0e0e4; display:flex; gap:16px; flex-wrap:wrap; align-items:center; justify-content:space-between;"><span style="font-size:15px; color:#6e6e73;">Bereit für dein eigenes Tischkraftwerk?</span><a href="/shop/" style="cursor:pointer; display:inline-flex; align-items:center; gap:9px; background:#111113; color:#ffffff; border-radius:980px; padding:12px 26px; font-weight:600; font-size:14.5px;">Zum Shop</a></div></div></div>';
}

/* ---------------- ÜBER UNS ---------------- */
function pageAbout(){
  return '<div style="background:#ffffff;">'
  + '<section style="background:#0a0a0c; padding:120px 32px;"><div style="max-width:860px; margin:0 auto; text-align:center;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:16px;">Über uns</div><h1 style="margin:0 0 22px; font-size:50px; line-height:1.14; font-weight:700; letter-spacing:-0.02em; color:#ffffff;">Wir bringen die Energiewende auf deine Terrasse.</h1><p style="margin:0 auto; max-width:560px; font-size:17px; line-height:1.65; color:#86868b;">Sustable steht für Solarmöbel, die Design und nachhaltige Energie verbinden – durchdacht entwickelt, regional und fair gefertigt in Deutschland.</p></div></section>'
  + '<section style="padding:110px 32px; background:#ffffff;"><div class="grid2" style="max-width:1080px; margin:0 auto; display:grid; grid-template-columns:1fr 1fr; gap:60px; align-items:center;"><div style="border-radius:22px; overflow:hidden; height:460px;"><img src="https://sustable.eu/wp-content/uploads/2026/01/DSC02954-min-1365x2048.jpg" alt="Sustable Solartisch auf einer Terrasse" loading="lazy" style="width:100%; height:100%; object-fit:cover; display:block;"></div><div><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Unsere Geschichte</div><h2 style="margin:0 0 20px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Aus einer einfachen Frage entstand eine neue Möbelkategorie.</h2><p style="margin:0 0 16px; font-size:15.5px; line-height:1.75; color:#6e6e73;">Warum verschenken wir wertvolle Sonnenfläche auf Terrasse und Balkon, während Gartenmöbel dort ohnehin den ganzen Tag in der Sonne stehen? Aus dieser Idee wurde der Sustable Solartisch.</p><p style="margin:0; font-size:15.5px; line-height:1.75; color:#6e6e73;">Als Teil von e-con verbinden wir technisches Know-how aus der Energiebranche mit hochwertigem Möbeldesign – und machen saubere Energie für jeden zugänglich, ganz ohne eigene Dachfläche.</p></div></div></section>'
  + '<section style="padding:70px 32px; background:#f5f5f7;"><div class="grid3" style="max-width:1080px; margin:0 auto; display:grid; grid-template-columns:1fr 1fr 1fr; gap:24px; text-align:center;"><div><div style="font-size:44px; font-weight:800; letter-spacing:-0.02em; color:#1d1d1f;">2024</div><div style="font-size:14.5px; color:#6e6e73; margin-top:6px;">Gegründet, powered by e-con</div></div><div><div style="font-size:44px; font-weight:800; letter-spacing:-0.02em; color:#1d1d1f;"><span data-countup="10">10</span> Jahre</div><div style="font-size:14.5px; color:#6e6e73; margin-top:6px;">Garantie auf jeden Solartisch</div></div><div><div style="font-size:44px; font-weight:800; letter-spacing:-0.02em; color:#1d1d1f;"><span data-countup="100">100</span> %</div><div style="font-size:14.5px; color:#6e6e73; margin-top:6px;">Made &amp; Support in Germany</div></div></div></section>'
  + '<section style="padding:110px 32px; background:#ffffff;"><div style="max-width:1080px; margin:0 auto;"><h2 style="margin:0 0 44px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f; text-align:center;">Wofür wir stehen.</h2><div class="grid3" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:20px;">'
  + benefit('<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"></path><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"></path>','Nachhaltigkeit','Saubere Energie und langlebige Materialien statt Wegwerfprodukte – ein Beitrag zu einer besseren Zukunft.')
  + benefit('<path d="M12 19l7-7 3 3-7 7-3-3z"></path><path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"></path><path d="M2 2l7.586 7.586"></path><circle cx="11" cy="11" r="2"></circle>','Design','Technik, die man nicht verstecken muss. Unsere Solartische sind ein Statement für modernes, zeitloses Design.')
  + benefit('<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"></path><circle cx="12" cy="10" r="3"></circle>','Regionalität','Kurze Wege, faire Arbeitsbedingungen und Fertigung in Deutschland – Qualität, der du vertrauen kannst.')
  + '</div></div></section>'
  + '<section style="padding:0 32px 110px; background:#ffffff;"><div style="max-width:1080px; margin:0 auto; background:#0a0a0c; border-radius:26px; padding:64px 50px; text-align:center;"><h2 style="margin:0 0 16px; font-size:32px; font-weight:700; letter-spacing:-0.02em; color:#ffffff;">Lerne Sustable kennen.</h2><p style="margin:0 auto 32px; max-width:480px; font-size:15.5px; line-height:1.6; color:#86868b;">Ob privat auf der Terrasse oder als Händler im Sortiment – wir freuen uns auf dich.</p><div style="display:flex; gap:14px; justify-content:center; flex-wrap:wrap;"><a href="/shop/" style="cursor:pointer; display:inline-flex; align-items:center; gap:9px; background:#ffffff; color:#111113; border-radius:980px; padding:14px 30px; font-weight:600; font-size:15px;">Zum Shop</a><a href="/business/" style="cursor:pointer; display:inline-flex; align-items:center; background:transparent; color:#ffffff; border:1.5px solid rgba(255,255,255,0.4); border-radius:980px; padding:13px 28px; font-weight:600; font-size:15px;">Für Händler</a></div></div></section>'
  + '</div>';
}

/* ---------------- MEHR ERFAHREN ---------------- */
function mehrRow(img, title, text, imgLeft){
  var imgBlock = '<div style="border-radius:22px; overflow:hidden;'+(img.bg?' background:#f5f5f7;':'')+'"><img src="'+img.src+'" alt="'+esc(title)+'" loading="lazy" style="width:100%; height:340px; object-fit:'+(img.fit||'cover')+'; display:block;"></div>';
  var textBlock = '<div><h2 style="margin:0 0 16px; font-size:27px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;">'+title+'</h2><p style="margin:0; font-size:15.5px; line-height:1.75; color:#6e6e73;">'+text+'</p></div>';
  return '<div class="grid2" style="display:grid; grid-template-columns:1fr 1fr; gap:56px; align-items:center;">'+(imgLeft?imgBlock+textBlock:textBlock+imgBlock)+'</div>';
}
function pageMehr(){
  return '<div style="background:#ffffff;">'
  + '<section style="background:#f5f5f7; padding:90px 32px;"><div class="grid2" style="max-width:1100px; margin:0 auto; display:grid; grid-template-columns:1.2fr 1fr; gap:60px; align-items:center;"><div><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Mehr erfahren</div><h1 style="margin:0 0 22px; font-size:46px; line-height:1.15; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Mehr Informationen zu unseren Solartischen.</h1><p style="margin:0 0 32px; font-size:17px; line-height:1.7; color:#6e6e73;">Unsere Solartische vereinen modernes Design mit nachhaltiger Energiegewinnung. Sie bieten die volle Funktionalität eines klassischen Gartentisches – mit dem zusätzlichen Vorteil, Sonnenenergie in Strom umzuwandeln.</p><a href="/shop/" style="cursor:pointer; display:inline-flex; align-items:center; gap:9px; background:#111113; color:#ffffff; border-radius:980px; padding:13px 28px; font-weight:600; font-size:15px;">Jetzt entdecken '+arrowW+'</a></div><div style="border-radius:22px; overflow:hidden; max-height:440px;"><img src="https://sustable.eu/wp-content/uploads/2026/01/DSC02954-min-1365x2048.jpg" alt="Sustable Solartisch im Detail" loading="lazy" style="width:100%; height:440px; object-fit:cover; display:block;"></div></div></section>'
  + '<section class="mehr-flex" style="padding:90px 32px; max-width:1100px; margin:0 auto; display:flex; flex-direction:column; gap:90px;">'
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2026/01/DSC02941-min-2048x1365.jpg'}, 'Wärmeentwicklung und Langlebigkeit.', 'Auch unsere Solarplatte erwärmt sich durch direkte Sonne. Durch die Stromerzeugung heizt sie sich jedoch weniger auf als Kunststoff- oder Metallplatten. Die Solartische sind für den dauerhaften Außeneinsatz gemacht und halten Regen, Schnee und Hagel stand – ganzjährig und ohne Funktionsverlust.', true)
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2025/11/ChatGPT-Image-26.-Juni-2025-16_46_53-e1762325531499.png'}, 'Pflegeleicht und unkompliziert.', 'Die Glasoberfläche kann einfach mit einem feuchten Tuch und mildem Reinigungsmittel gereinigt werden. Kratzer werden durch das gehärtete Glas vermieden.', false)
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2025/10/One_7.avif', fit:'contain', bg:true}, 'Technische Eigenschaften und Stabilität.', 'Die Solarplatten bestehen aus leistungsstarken Modulen mit einem stabilen Aluminiumrahmen. Die Solarzellen sind dauerhaft mit der Glasplatte verbunden, sodass die Konstruktion widerstandsfähig bleibt. Selbst hohe Schneelasten oder starke Stöße können der Oberfläche kaum etwas anhaben.', true)
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2025/10/One_6.avif', fit:'contain', bg:true}, 'Effizienz und Standortwahl.', 'Die Stromausbeute hängt – wie bei allen Solarmodulen – von der Sonneneinstrahlung ab. Es empfiehlt sich eine Platzierung an einem möglichst sonnigen Ort. Bereits kleine Schatten, etwa von einem Sonnenschirm-Stiel, können den Wirkungsgrad beeinträchtigen.', false)
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2025/11/ChatGPT-Image-26.-Juni-2025-16_31_20-e1762326075709.png'}, 'Einspeisen über eine Steckdose.', 'Der erzeugte Solarstrom wird direkt über eine haushaltsübliche Steckdose ins Hausnetz eingespeist. Der Wechselrichter verfügt über einen automatischen Netz- und Anlagenschutz, der die Einspeisung sofort unterbricht, sobald der Stecker gezogen wird.', true)
  + mehrRow({src:'https://sustable.eu/wp-content/uploads/2025/11/Bildschirmfoto-2025-06-26-um-17.01.18-e1762326152515.png'}, 'Kein Einfluss auf den Nutzungskomfort.', 'Die stabile Bauweise ermöglicht eine uneingeschränkte Nutzung im Alltag. Geschirr, Gläser oder andere Gegenstände können bedenkenlos direkt auf der Glasplatte abgestellt werden.', false)
  + '</section>'
  + '<section style="padding:0 32px 110px;"><div style="max-width:1100px; margin:0 auto; background:#f5f5f7; border-radius:22px; padding:50px; display:flex; align-items:center; justify-content:space-between; gap:30px; flex-wrap:wrap;"><div><h2 style="margin:0 0 8px; font-size:25px; font-weight:700; letter-spacing:-0.01em;">Bereit für dein eigenes Tischkraftwerk?</h2><p style="margin:0; font-size:14.5px; color:#6e6e73;">Sustable ONE+ Edelstahl · 1.750 € · 10 Jahre Garantie</p></div><div style="display:flex; gap:14px; flex-wrap:wrap;"><button type="button" data-add="one-plus" style="cursor:pointer; display:inline-flex; align-items:center; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:13px 28px; font-weight:600; font-size:15px;">In den Warenkorb</button><a href="'+productPath(prod('one-plus'))+'" style="cursor:pointer; display:inline-flex; align-items:center; background:transparent; color:#1d1d1f; border:1.5px solid #c7c7cc; border-radius:980px; padding:12px 26px; font-weight:600; font-size:15px;">Zum Produkt</a></div></div></section>'
  + '</div>';
}

/* ---------------- BUSINESS ---------------- */
function pageBusiness(){
  var CAL='https://calendar.app.google/j1BujJkMVCzWWSyg6';
  function adv(svg,title,text){ return '<div style="background:#ffffff; border-radius:20px; padding:34px;"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#1d1d1f" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" style="margin-bottom:16px;" aria-hidden="true">'+svg+'</svg><h3 style="margin:0 0 8px; font-size:18px; font-weight:700;">'+title+'</h3><p style="margin:0; font-size:14.5px; line-height:1.65; color:#6e6e73;">'+text+'</p></div>'; }
  function contact(img,name,mail,tel,telHref){ return '<div style="background:#f5f5f7; border-radius:22px; padding:38px; text-align:center;"><img src="'+img+'" alt="'+esc(name)+'" loading="lazy" width="110" height="110" style="width:110px; height:110px; border-radius:50%; object-fit:cover; margin:0 auto 18px; display:block;"><div style="font-weight:700; font-size:18px; margin-bottom:4px;">'+name+'</div><div style="font-size:13.5px; color:#86868b; margin-bottom:16px;">Vertrieb &amp; Partnermanagement</div><div style="font-size:14.5px; line-height:1.9; color:#424245; margin-bottom:22px;"><a href="mailto:'+mail+'" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">'+mail+'</a><br><a href="'+telHref+'" style="color:#1d1d1f; font-weight:600;">'+tel+'</a></div><a href="'+CAL+'" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; background:#111113; color:#ffffff; border-radius:980px; padding:11px 24px; font-weight:600; font-size:14px;">Termin buchen</a></div>'; }
  return '<div>'
  + '<section style="background:#0a0a0c; padding:110px 32px;"><div style="max-width:1080px; margin:0 auto; text-align:center;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:16px;">Sustable Business</div><h1 style="margin:0 0 24px; font-size:52px; line-height:1.12; font-weight:700; letter-spacing:-0.02em; color:#ffffff;">Solartische für Unternehmen &amp; Gastronomie.</h1><div style="display:flex; gap:12px; justify-content:center; flex-wrap:wrap; margin-bottom:42px;"><span style="background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.16); color:#ffffff; font-size:13px; font-weight:600; padding:8px 18px; border-radius:980px;">Made in Germany</span><span style="background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.16); color:#ffffff; font-size:13px; font-weight:600; padding:8px 18px; border-radius:980px;">10 Jahre Garantie</span><span style="background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.16); color:#ffffff; font-size:13px; font-weight:600; padding:8px 18px; border-radius:980px;">100 % technischer Kundensupport</span></div><div style="display:flex; gap:14px; justify-content:center; flex-wrap:wrap;"><a href="'+CAL+'" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; gap:9px; background:#ffffff; color:#111113; border-radius:980px; padding:15px 32px; font-weight:600; font-size:16px;">Jetzt Termin buchen '+arrowD+'</a><a href="https://sustable.eu/wp-content/uploads/2026/03/Broschuere.pdf" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; background:transparent; color:#ffffff; border:1.5px solid rgba(255,255,255,0.4); border-radius:980px; padding:14px 30px; font-weight:600; font-size:16px;">Broschüre herunterladen</a></div></div></section>'
  + '<section style="padding:110px 32px; background:#ffffff;"><div class="grid2" style="max-width:1080px; margin:0 auto; display:grid; grid-template-columns:1fr 1fr; gap:60px; align-items:center;"><div><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Design trifft Energie</div><h2 style="margin:0 0 20px; font-size:36px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Die neue Produktkategorie für den modernen Outdoor-Markt.</h2><p style="margin:0 0 16px; font-size:15.5px; line-height:1.75; color:#6e6e73;">Wir verbinden zeitlose Ästhetik mit nachhaltiger Innovation. Unsere Solartische sind mehr als nur Möbel – sie sind ein Statement für einen nachhaltigen Lifestyle, verpackt in hochwertigem Design.</p><p style="margin:0 0 30px; font-size:15.5px; line-height:1.75; color:#6e6e73;">Sie sind Category Manager oder Einkäufer und suchen nach einem echten USP für Ihr Sortiment? Entdecken Sie mit Sustable eine völlig neue Möbelkategorie, die Design und Funktion perfekt vereint.</p><a href="'+CAL+'" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; gap:9px; background:#111113; color:#ffffff; border-radius:980px; padding:13px 28px; font-weight:600; font-size:15px;">Unverbindliches Angebot anfragen</a></div><div style="background:#f5f5f7; border-radius:22px; padding:40px; display:flex; align-items:center; justify-content:center;"><img src="https://sustable.eu/wp-content/uploads/2025/10/One_1.avif" alt="Sustable ONE+ für Geschäftskunden" loading="lazy" style="max-width:100%; height:auto; display:block;"></div></div></section>'
  + '<section style="padding:100px 32px; background:#f5f5f7;"><div style="max-width:1080px; margin:0 auto;"><h2 style="margin:0 0 44px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f; text-align:center;">Ihre Vorteile als Geschäftspartner.</h2><div class="grid3" style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:20px;">'
  + adv('<path d="M3 3v16a2 2 0 0 0 2 2h16"></path><path d="M7 14l4-4 3 3 5-6"></path>','Exklusive Konditionen','Attraktive Handelsmargen und faire Partnerkonditionen für Ihr Sortiment.')
  + adv('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path>','Persönliche Betreuung','Feste Ansprechpartner, Schulung Ihres Teams und Unterstützung am POS.')
  + adv('<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1 1 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path>','Erstklassige Qualität','Made in Germany, 10 Jahre Garantie und 100 % technischer Kundensupport.')
  + '</div></div></section>'
  + '<section style="padding:110px 32px; background:#ffffff;"><div style="max-width:880px; margin:0 auto;"><h2 style="margin:0 0 14px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f; text-align:center;">Ihre Ansprechpartner.</h2><p style="margin:0 auto 48px; max-width:520px; text-align:center; font-size:15.5px; color:#6e6e73; line-height:1.6;">Buchen Sie direkt einen Termin – wir melden uns innerhalb von 24 Stunden.</p><div class="grid2" style="display:grid; grid-template-columns:1fr 1fr; gap:24px;">'
  + contact('https://sustable.eu/wp-content/uploads/2026/03/louis-mueller-q.jpg','Louis Müller','louis.mueller@sustable.eu','+49 1514 1872588','tel:+4915141872588')
  + contact('https://sustable.eu/wp-content/uploads/2026/03/nils-schreitmueller-q.jpg','Nils Schreitmüller','nils.schreitmueller@sustable.eu','+49 159 01129733','tel:+4915901129733')
  + '</div></div></section>'
  + '<section style="padding:90px 32px; background:#0a0a0c;"><div style="max-width:880px; margin:0 auto; text-align:center;"><h2 style="margin:0 0 28px; font-size:34px; font-weight:700; letter-spacing:-0.02em; color:#ffffff;">Setzen wir gemeinsam neue Maßstäbe im Möbelhandel.</h2><a href="'+CAL+'" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; gap:9px; background:#ffffff; color:#111113; border-radius:980px; padding:15px 32px; font-weight:600; font-size:16px;">Jetzt Kontakt aufnehmen '+arrowD+'</a></div></section>'
  + '</div>';
}

/* ---------------- HÄNDLERSUCHE ---------------- */
function pageHaendler(){
  var cards = DEALERS.map(function(d){
    return '<div style="background:#ffffff; border-radius:20px; padding:28px;"><div style="display:flex; justify-content:space-between; align-items:baseline; gap:12px; margin-bottom:4px;"><h2 style="margin:0; font-size:18px; font-weight:700; color:#1d1d1f;">'+d.name+'</h2><span class="dealer-dist" data-dealer-dist="'+d.id+'" style="font-size:13.5px; font-weight:700; color:#e8821d; white-space:nowrap;"></span></div>'
    + '<div style="font-size:13.5px; color:#86868b; margin-bottom:14px;">'+d.untertitel+'</div>'
    + '<address style="font-style:normal; font-size:14.5px; line-height:1.7; color:#424245; margin-bottom:8px;">'+d.strasse+'<br>'+d.ort+'</address>'
    + '<div style="font-size:14.5px; line-height:1.8; color:#424245; margin-bottom:6px;">Tel. <a href="'+d.telHref+'" style="color:#1d1d1f; font-weight:600;">'+d.tel+'</a><br><a href="'+d.mailHref+'" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">'+d.mail+'</a></div>'
    + (d.zeiten1?'<div style="font-size:13.5px; line-height:1.7; color:#424245; background:#f5f5f7; border-radius:12px; padding:10px 14px; margin:10px 0 4px;"><span style="font-weight:600;">Öffnungszeiten</span><br>'+d.zeiten1+'<br>'+d.zeiten2+'</div>':'')
    + '<div style="display:flex; gap:10px; margin-top:16px; flex-wrap:wrap;"><button type="button" data-dealer-show="'+d.id+'" style="cursor:pointer; display:inline-flex; align-items:center; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:9px 18px; font-weight:600; font-size:13.5px;">Auf Karte zeigen</button><a href="'+d.routeHref+'" target="_blank" rel="noopener" style="display:inline-flex; align-items:center; background:transparent; color:#1d1d1f; border:1.5px solid #c7c7cc; border-radius:980px; padding:8px 17px; font-weight:600; font-size:13.5px;">Route planen</a></div></div>';
  }).join('');
  return '<div style="background:#f5f5f7; padding:80px 32px 110px; min-height:70vh;"><div style="max-width:1180px; margin:0 auto;"><div style="text-align:center; margin-bottom:44px;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Händlersuche</div><h1 style="margin:0 0 16px; font-size:46px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Sustable Händler finden.</h1><p style="margin:0; font-size:17px; color:#6e6e73;">Gib deine Stadt oder Postleitzahl ein und finde den nächsten Sustable-Fachhändler.</p></div>'
  + '<div style="display:flex; gap:12px; max-width:600px; margin:0 auto 18px;"><input type="text" id="search-input" placeholder="Stadt oder Postleitzahl eingeben" aria-label="Stadt oder Postleitzahl" style="flex:1; padding:14px 22px; font-size:15.5px; border:1px solid #d2d2d7; border-radius:980px; background:#ffffff; color:#1d1d1f; outline:none;"><button type="button" id="search-submit" style="cursor:pointer; display:inline-flex; align-items:center; background:#111113; color:#ffffff; border:0; border-radius:980px; padding:14px 30px; font-weight:600; font-size:15px;">Suchen</button></div>'
  + '<div id="search-info" style="text-align:center; margin-bottom:24px; font-size:14.5px; font-weight:600; color:#1d1d1f; min-height:18px;"></div>'
  + '<div class="grid2" style="display:grid; grid-template-columns:1.4fr 1fr; gap:22px; align-items:start; margin-top:28px;"><div id="map" style="height:540px; border-radius:22px; overflow:hidden; background:#e8e8ed;"></div><div style="display:flex; flex-direction:column; gap:16px;">'+cards+'<div style="font-size:13px; color:#86868b; line-height:1.6; padding:0 6px;">Du bist Händler und möchtest Sustable in dein Sortiment aufnehmen? <a href="/business/" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">Werde Partner →</a></div></div></div></div></div>';
}

/* ---------------- SOLARTISCH (Keyword-Landingpage) ---------------- */
function pageSolartisch(){
  return '<div style="background:#ffffff;">'
  + '<section style="background:#f5f5f7; padding:90px 32px;"><div style="max-width:860px; margin:0 auto; text-align:center;"><div style="color:#86868b; font-weight:600; font-size:13px; letter-spacing:0.12em; text-transform:uppercase; margin-bottom:14px;">Ratgeber</div><h1 style="margin:0 0 22px; font-size:48px; line-height:1.14; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Was ist ein Solartisch?</h1><p style="margin:0 auto; max-width:600px; font-size:18px; line-height:1.65; color:#424245;">Ein Solartisch ist ein vollwertiger Gartentisch mit integriertem Solarmodul. Er erzeugt sauberen Strom direkt auf deiner Terrasse – und speist ihn per Steckdose ins Hausnetz ein. Hier erfährst du, wie er funktioniert, was er bringt und was er kostet.</p></div></section>'
  + '<section style="padding:80px 32px; max-width:820px; margin:0 auto;"><div style="display:flex; flex-direction:column; gap:40px;">'
  + '<div><h2 style="margin:0 0 12px; font-size:28px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;">Wie funktioniert ein Solartisch?</h2><p style="margin:0; font-size:16.5px; line-height:1.8; color:#2c2c2e;">In der Tischplatte sitzt ein leistungsstarkes Photovoltaik-Modul. Es wandelt Sonnenlicht in Gleichstrom um, den ein integrierter 500 W-Mikro-Wechselrichter in haushaltsüblichen Wechselstrom umwandelt. Über eine normale Außensteckdose fließt dieser Strom direkt in dein Hausnetz – ganz ohne Installation, nach dem Plug-&-Play-Prinzip eines Balkonkraftwerks.</p></div>'
  + '<div><h2 style="margin:0 0 12px; font-size:28px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;">Wie viel Strom erzeugt ein Solartisch?</h2><p style="margin:0; font-size:16.5px; line-height:1.8; color:#2c2c2e;">Mit einem 465 Wp-Modul erzeugt der Sustable ONE+ je nach Standort und Sonneneinstrahlung rund 450–510 kWh pro Jahr. Das entspricht ungefähr dem Jahresverbrauch eines effizienten Kühlschranks. Wie viel du damit konkret sparst, kannst du im <a href="/#rechner" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">Ersparnis-Rechner</a> ausrechnen.</p></div>'
  + '<div><h2 style="margin:0 0 12px; font-size:28px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;">Was kostet ein Solartisch?</h2><p style="margin:0; font-size:16.5px; line-height:1.8; color:#2c2c2e;">Die Sustable Solartische starten bei 1.190 € (Sustable mini) und reichen bis 1.750 € für das Edelstahl-Flaggschiff Sustable ONE+. Als Tischkraftwerk mit integrierter Photovoltaik unter 30 kWp gilt für den privaten Gebrauch der Umsatzsteuersatz von 0 % nach § 12 Abs. 3 UStG.</p></div>'
  + '<div><h2 style="margin:0 0 12px; font-size:28px; font-weight:700; letter-spacing:-0.01em; color:#1d1d1f;">Muss ein Solartisch angemeldet werden?</h2><p style="margin:0; font-size:16.5px; line-height:1.8; color:#2c2c2e;">Da die Leistung unter der 800 W-Grenze für Balkonkraftwerke liegt, ist keine Genehmigung nötig. Seit April 2024 genügt eine einfache Anmeldung im Marktstammdatenregister. Weitere Antworten findest du in unseren <a href="/faq/" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">häufigen Fragen</a>.</p></div>'
  + '</div></section>'
  + '<section style="padding:0 32px 110px;"><div style="max-width:820px; margin:0 auto; background:#0a0a0c; border-radius:26px; padding:56px 44px; text-align:center;"><h2 style="margin:0 0 14px; font-size:30px; font-weight:700; letter-spacing:-0.02em; color:#ffffff;">Den Sustable Solartisch entdecken.</h2><p style="margin:0 auto 30px; max-width:480px; font-size:15.5px; line-height:1.6; color:#86868b;">Premium-Design, Made im Allgäu, 10 Jahre Garantie.</p><a href="'+productPath(prod('one-plus'))+'" style="display:inline-flex; align-items:center; gap:9px; background:#ffffff; color:#111113; border-radius:980px; padding:14px 30px; font-weight:600; font-size:15px;">Zum Sustable ONE+ '+arrowD+'</a></div></section>'
  + '</div>';
}

/* ---------------- WARENKORB / CHECKOUT (JS-gerendert, noindex) ---------------- */
function pageCart(){
  return '<div style="background:#f5f5f7; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:1080px; margin:0 auto;"><h1 style="margin:0 0 36px; font-size:40px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Warenkorb</h1><div id="cart-app"><p style="color:#6e6e73;">Warenkorb wird geladen …</p></div></div></div>';
}
function pageCheckout(){
  return '<div style="background:#f5f5f7; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:740px; margin:0 auto;"><h1 style="margin:0 0 10px; font-size:40px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">Kasse</h1><div id="checkout-app"><p style="color:#6e6e73;">Kasse wird geladen …</p></div></div></div>';
}

/* ---------------- Rechtstexte (Platzhalter, noindex) ---------------- */
function pageLegal(title, officialUrl){
  return '<div style="background:#ffffff; padding:80px 32px 120px; min-height:70vh;"><div style="max-width:760px; margin:0 auto;"><h1 style="margin:0 0 24px; font-size:40px; font-weight:700; letter-spacing:-0.02em; color:#1d1d1f;">'+esc(title)+'</h1>'
  + '<div style="background:#f5f5f7; border-radius:16px; padding:24px 28px; font-size:15px; line-height:1.7; color:#424245;"><p style="margin:0 0 12px;"><strong>Hinweis:</strong> Der rechtsverbindliche Text für „'+esc(title)+'" wird hier eingepflegt. Bis dahin gilt die aktuell veröffentlichte Fassung:</p><p style="margin:0;"><a href="'+officialUrl+'" target="_blank" rel="noopener" style="color:#1d1d1f; font-weight:600; text-decoration:underline;">'+esc(title)+' ansehen →</a></p></div></div></div>';
}
